# the alpha parameter
alpha: 0.125
# global data-size (excluding the number of ghost layers for boundary conditions)
global_size: { height: 60, width: 40 }
# degree of parallelism (number of blocks in each dimension)
parallelism: { height: 2, width: 2 }

pdi:
  metadata:
    local_size: {type: array, subtype: int, size: 2}
    pcoord: {type: array, subtype: int, size: 2}
  data:
    iteration: int
    temp: {type: array, subtype: double, size: ['$local_size[0]', '$local_size[1]']}
  plugins:
    trace:
    pycall:
      on_event:
        loop:
          with: { iter_id: $iteration, source_field: $temp, py_pcoord: $pcoord }
          exec: |
            import matplotlib.pyplot as plt
            plt.imshow(source_field[1:-1, 1:-1], origin='lower', cmap='viridis', vmax=200)
            plt.colorbar()
            plt.axis('off')
            plt.savefig("output_r"+str(py_pcoord[0])+"x"+str(py_pcoord[1])+"_iter"+str(iter_id))
            plt.close()
            
            # import function from a user python file
            from myplot import plot_global_image
            plot_global_image(source_field, py_pcoord, iter_id)

            # Remark: 
            #     In this function, the data "psize" (see main.c) is recomputed with "pcoord".
            #     In a real case, it is better to pass this argument to "plot_global_image"
            #     to avoid communication as the parameter "pcoord". This corresponds to:
            #          1. define "psize" as metadata
            #          2. expose "psize" to pdi in main.c
            #          3. Add "psize" in the list of variables shared with python in line 22 ("with" keyword)
