# the alpha parameter
alpha: 0.125
# global data-size (excluding the number of ghost layers for boundary conditions)
global_size: { height: 60, width: 12 }
# degree of parallelism (number of blocks in each dimension)
parallelism: { height: 2, width: 2 }

pdi:
  metadata:
    local_size: {type: array, subtype: int, size: 2}
    rank: int
    pcoord: {type: array, subtype: int, size: 2}
    psize: {type: array, subtype: int, size: 2}
    max_iter: int
  data:
    iteration: int
    temp: {type: array, subtype: double, size: ['$local_size[0]', '$local_size[1]']}
  plugins:
    trace: 
    mpi:
    decl_hdf5:
      