# the alpha parameter
alpha: 0.125
# global data-size (excluding the number of ghost layers for boundary conditions)
global_size: { height: 60, width: 12 }
# degree of parallelism (number of blocks in each dimension)
parallelism: { height: 2, width: 2 }

pdi:
  metadata:
    local_size: {type: array, subtype: int, size: 2}
  data:
    iteration: int
    temp: {type: array, subtype: double, size: ['$local_size[0]', '$local_size[1]']}
  plugins:
    trace:
    pycall:
      on_data:
        temp:
          #*** specifies the input parameters (variables) to pass to Python as a set of "$-expressions" (expressions must be defined in .yml script)
          with: { source_field: $temp }
          #*** add exec keyword of pycall plugin and after the colon, add a space and a vertical bar
          exec: |
            import numpy as np
