# the alpha parameter
alpha: 0.125
# global data-size (excluding the number of ghost layers for boundary conditions)
global_size: { height: 60, width: 40 }
# degree of parallelism (number of blocks in each dimension)
parallelism: { height: 2, width: 2 }

pdi:
  metadata:
    local_size: {type: array, subtype: int, size: 2}
    pcoord: {type: array, subtype: int, size: 2}
  data:
    iteration: int
    temp: {type: array, subtype: double, size: ['$local_size[0]', '$local_size[1]']}
  plugins:
    trace:
    pycall:
      on_event:
        loop:
          with: { iter_id: $iteration, source_field: $temp, coord: $pcoord}
          exec: |
            import matplotlib.pyplot as plt
            plt.imshow(source_field[1:-1, 1:-1], cmap='viridis', vmax=200)
            plt.colorbar()
            plt.axis('off')
            plt.savefig("output_r"+str(coord[0])+"x"+str(coord[1])+"_iter"+str(iter_id))
            plt.close()
            