# the alpha parameter
alpha: 0.125
# global data-size (excluding the number of ghost layers for boundary conditions)
global_size: { height: 60, width: 40 }
# degree of parallelism (number of blocks in each dimension)
parallelism: { height: 1, width: 1 }
# Address of the dask scheduler
dask_addr: tcp://127.0.0.1:8786

pdi:
  metadata:
    local_size: {type: array, subtype: int, size: 2}
    pcoord: {type: array, subtype: int, size: 2}
    psize: {type: array, subtype: int, size: 2}
    rank: int
    comm_size: int
    dask_addr: {type: array, subtype: char, size: 20}
  data:
    iteration: int
    temp: {type: array, subtype: double, size: ['$local_size[0]', '$local_size[1]']}
  plugins:
    mpi:
    trace:
    pycall:
      on_event:
        init:
          with: { rank: $rank, psize: $psize, dask_addr: $dask_addr, local_size: $local_size }
          exec: |
            print(f"init: rank={rank}, psize={psize}, dask_addr={dask_addr}, local_size={local_size}")
        loop:
          with: { iter_id: $iteration, source_field: $temp, py_pcoord: $pcoord }
          exec: |
            print(f"loop: iteration={iter_id}, pcoord={py_pcoord}")
